language: go

go:
  - "1.11"

matrix:
  include:
    - os:
        - osx
        - linux
      install:
        - make dependencies
      script:
        - make tests
        - make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os:
        - linux
      install:
        - make dependencies
      script:
        - make tests
        - make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  allow_failures:
    - os: windows
      script:
        - go get -t -v ./...
        - go test -v ./...