language: go

go:
  - "1.11"

matrix:
  include:
    - stage: Build, Generate & Test Metadata
      os:
        - osx
        - linux
      install:
        - make dependencies
      script:
        - make tests
        - make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: Test Metadata (Windows)
      os: windows
      script:
        - go get -t -v ./...
        - go test -v ./...