package monetary

var (
	localeNames = LocaleNames{
		"ru_RU.ISO8859-5",
		"ko_KR.UTF-8",
		"sk_SK.UTF-8",
		"zh_HK",
		"en_US",
		"fr_CH",
		"it_CH.ISO8859-15",
		"sl_SI.UTF-8",
		"af_ZA",
		"bg_BG.CP1251",
		"de_AT.ISO8859-15",
		"fr_BE.ISO8859-15",
		"fr_CH.ISO8859-1",
		"de_AT.ISO8859-1",
		"en_AU.ISO8859-1",
		"fi_FI.ISO8859-1",
		"ro_RO.UTF-8",
		"en_GB",
		"et_EE",
		"is_IS.ISO8859-1",
		"fr_CH.UTF-8",
		"it_IT.UTF-8",
		"kk_KZ.PT154",
		"lt_LT.ISO8859-13",
		"pt_PT.ISO8859-15",
		"af_ZA.ISO8859-1",
		"ca_ES.ISO8859-15",
		"es_ES.UTF-8",
		"tr_TR.UTF-8",
		"zh_TW.Big5",
		"es_ES.ISO8859-1",
		"es_ES.ISO8859-15",
		"sr_YU.ISO8859-5",
		"de_CH",
		"en_AU",
		"en_GB.US-ASCII",
		"en_GB.ISO8859-15",
		"hu_HU.ISO8859-2",
		"is_IS.UTF-8",
		"ru_RU",
		"ru_RU.UTF-8",
		"be_BY.CP1131",
		"bg_BG.UTF-8",
		"en_AU.ISO8859-15",
		"sk_SK",
		"zh_CN",
		"zh_TW",
		"ja_JP.UTF-8",
		"ko_KR.CP949",
		"no_NO.ISO8859-1",
		"de_DE.ISO8859-15",
		"en_NZ.ISO8859-15",
		"he_IL.UTF-8",
		"ja_JP.eucJP",
		"nl_NL.ISO8859-1",
		"pl_PL.ISO8859-2",
		"pt_PT",
		"sr_YU.UTF-8",
		"en_CA",
		"en_NZ.UTF-8",
		"fr_CA.UTF-8",
		"kk_KZ",
		"pl_PL",
		"de_AT",
		"en_US.UTF-8",
		"hr_HR.UTF-8",
		"et_EE.ISO8859-15",
		"fi_FI.UTF-8",
		"kk_KZ.UTF-8",
		"nl_BE",
		"no_NO.ISO8859-15",
		"C",
		"am_ET.UTF-8",
		"en_CA.ISO8859-15",
		"pt_BR.ISO8859-1",
		"en_AU.UTF-8",
		"es_ES",
		"fr_BE.ISO8859-1",
		"hr_HR",
		"lt_LT.UTF-8",
		"ca_ES.UTF-8",
		"cs_CZ.ISO8859-2",
		"el_GR",
		"ro_RO.ISO8859-2",
		"sv_SE.ISO8859-1",
		"ca_ES.ISO8859-1",
		"en_US.ISO8859-15",
		"sv_SE.ISO8859-15",
		"fr_FR.UTF-8",
		"he_IL",
		"is_IS.ISO8859-15",
		"hy_AM.ARMSCII-8",
		"it_IT",
		"nl_NL.ISO8859-15",
		"no_NO",
		"uk_UA.UTF-8",
		"POSIX",
		"be_BY.ISO8859-5",
		"da_DK.ISO8859-1",
		"zh_CN.GB2312",
		"de_CH.ISO8859-1",
		"it_IT.ISO8859-1",
		"ko_KR.eucKR",
		"zh_CN.UTF-8",
		"de_AT.UTF-8",
		"fr_CA.ISO8859-15",
		"it_CH.ISO8859-1",
		"hy_AM.UTF-8",
		"it_CH",
		"pt_BR.UTF-8",
		"tr_TR.ISO8859-9",
		"en_IE.UTF-8",
		"en_NZ",
		"hu_HU",
		"en_GB.UTF-8",
		"nl_BE.ISO8859-15",
		"nl_NL.UTF-8",
		"sl_SI.ISO8859-2",
		"be_BY.UTF-8",
		"bg_BG",
		"da_DK.UTF-8",
		"en_CA.ISO8859-1",
		"pl_PL.UTF-8",
		"sr_YU",
		"sv_SE",
		"zh_TW.UTF-8",
		"da_DK",
		"de_CH.ISO8859-15",
		"en_AU.US-ASCII",
		"tr_TR",
		"zh_HK.Big5HKSCS",
		"be_BY.CP1251",
		"fr_BE",
		"lt_LT",
		"ja_JP",
		"ko_KR",
		"ro_RO",
		"ru_RU.CP866",
		"sl_SI",
		"af_ZA.ISO8859-15",
		"de_CH.UTF-8",
		"en_GB.ISO8859-1",
		"uk_UA.ISO8859-5",
		"zh_CN.GB18030",
		"zh_CN.eucCN",
		"et_EE.UTF-8",
		"fr_FR.ISO8859-1",
		"hr_HR.ISO8859-2",
		"ca_ES",
		"en_CA.US-ASCII",
		"en_CA.UTF-8",
		"hi_IN.ISCII-DEV",
		"lt_LT.ISO8859-4",
		"en_NZ.US-ASCII",
		"en_US.ISO8859-1",
		"eu_ES.UTF-8",
		"pt_PT.ISO8859-1",
		"uk_UA",
		"cs_CZ.UTF-8",
		"fr_CA.ISO8859-1",
		"it_IT.ISO8859-15",
		"en_US.US-ASCII",
		"eu_ES.ISO8859-1",
		"hu_HU.UTF-8",
		"ja_JP.SJIS",
		"no_NO.UTF-8",
		"de_DE.ISO8859-1",
		"el_GR.ISO8859-7",
		"el_GR.UTF-8",
		"pt_BR",
		"pt_PT.UTF-8",
		"uk_UA.KOI8-U",
		"it_CH.UTF-8",
		"nl_BE.UTF-8",
		"ru_RU.KOI8-R",
		"zh_HK.UTF-8",
		"be_BY",
		"cs_CZ",
		"de_DE.UTF-8",
		"eu_ES",
		"eu_ES.ISO8859-15",
		"is_IS",
		"af_ZA.UTF-8",
		"da_DK.ISO8859-15",
		"en_IE",
		"ru_RU.CP1251",
		"fr_BE.UTF-8",
		"fr_CH.ISO8859-15",
		"nl_BE.ISO8859-1",
		"sk_SK.ISO8859-2",
		"am_ET",
		"fi_FI.ISO8859-15",
		"fr_FR.ISO8859-15",
		"fr_CA",
		"fr_FR",
		"hy_AM",
		"nl_NL",
		"sr_YU.ISO8859-2",
		"de_DE",
		"en_NZ.ISO8859-1",
		"fi_FI",
		"sv_SE.UTF-8",
		"zh_CN.GBK",
	}
	metaData = map[string]localeInfo{
		"ru_RU.ISO8859-5": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{224, 227, 209, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ko_KR.UTF-8": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{226, 130, 169},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "sk_SK.UTF-8": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_HK": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_US": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CH": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_CH.ISO8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_SI.UTF-8": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_ZA": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_BG.CP1251": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{235, 226, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_AT.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_BE.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CH.ISO8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_AT.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_AU.ISO8859-1": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_FI.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ro_RO.UTF-8": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_GB": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{194, 163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_EE": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "is_IS.ISO8859-1": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "fr_CH.UTF-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_IT.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "kk_KZ.PT154": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{242, 227, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_LT.ISO8859-13": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_PT.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_ZA.ISO8859-1": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_ES.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_ES.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_TR.UTF-8": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_TW.Big5": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_ES.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_ES.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_YU.ISO8859-5": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{212, 216, 221},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_CH": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_AU": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_GB.US-ASCII": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_GB.ISO8859-15": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_HU.ISO8859-2": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "is_IS.UTF-8": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ru_RU": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_RU.UTF-8": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_BY.CP1131": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{224, 227, 161, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_BG.UTF-8": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{208, 187, 208, 178, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_AU.ISO8859-15": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sk_SK": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_CN": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{239, 191, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_TW": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ja_JP.UTF-8": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{194, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ko_KR.CP949": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "no_NO.ISO8859-1": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_DE.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_NZ.ISO8859-15": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "he_IL.UTF-8": {
			InternationalCurrencySymbol: "ILS",
			CurrencySymbol:              []byte{215, 169, 215, 151},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ja_JP.eucJP": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "nl_NL.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_PL.ISO8859-2": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 179},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_PT": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_YU.UTF-8": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_CA": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_NZ.UTF-8": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CA.UTF-8": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "kk_KZ": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{209, 130, 208, 179, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_PL": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 197, 130},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_AT": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_US.UTF-8": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_HR.UTF-8": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_EE.ISO8859-15": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_FI.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "kk_KZ.UTF-8": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{209, 130, 208, 179, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_BE": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_NO.ISO8859-15": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "C": {
			InternationalCurrencySymbol: "",
			CurrencySymbol:              nil,
			DecimalPoint:                nil,
			ThousandsSeparator:          nil,
			Grouping:                    []int8{0},
			PositiveSign:                nil,
			NegativeSign:                nil,
			FractionalDigits:            127,
		}, "am_ET.UTF-8": {
			InternationalCurrencySymbol: "ETB",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_CA.ISO8859-15": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_BR.ISO8859-1": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_AU.UTF-8": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_ES": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_BE.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_HR": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_LT.UTF-8": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_ES.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_CZ.ISO8859-2": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 232},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_GR": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ro_RO.ISO8859-2": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_SE.ISO8859-1": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_ES.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_US.ISO8859-15": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_SE.ISO8859-15": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_FR.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "he_IL": {
			InternationalCurrencySymbol: "ILS",
			CurrencySymbol:              []byte{215, 169, 215, 151},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "is_IS.ISO8859-15": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "hy_AM.ARMSCII-8": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{184, 240},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_IT": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_NL.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_NO": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_UA.UTF-8": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{208, 179, 209, 128, 208, 189, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "POSIX": {
			InternationalCurrencySymbol: "",
			CurrencySymbol:              nil,
			DecimalPoint:                nil,
			ThousandsSeparator:          nil,
			Grouping:                    []int8{0},
			PositiveSign:                nil,
			NegativeSign:                nil,
			FractionalDigits:            127,
		}, "be_BY.ISO8859-5": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{224, 227, 209, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_DK.ISO8859-1": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_CN.GB2312": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_CH.ISO8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_IT.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ko_KR.eucKR": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "zh_CN.UTF-8": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{239, 191, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_AT.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CA.ISO8859-15": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_CH.ISO8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hy_AM.UTF-8": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{212, 180, 213, 144},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_CH": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_BR.UTF-8": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_TR.ISO8859-9": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_IE.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{226, 130, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_NZ": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_HU": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_GB.UTF-8": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{194, 163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_BE.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_NL.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_SI.ISO8859-2": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_BY.UTF-8": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_BG": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{208, 187, 208, 178, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_DK.UTF-8": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_CA.ISO8859-1": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_PL.UTF-8": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 197, 130},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_YU": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_SE": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_TW.UTF-8": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_DK": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_CH.ISO8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_AU.US-ASCII": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_TR": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_HK.Big5HKSCS": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_BY.CP1251": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{240, 243, 225, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_BE": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_LT": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ja_JP": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{194, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ko_KR": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{226, 130, 169},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ro_RO": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_RU.CP866": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{224, 227, 161, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_SI": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_ZA.ISO8859-15": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_CH.UTF-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_GB.ISO8859-1": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_UA.ISO8859-5": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{211, 224, 221, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_CN.GB18030": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_CN.eucCN": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_EE.UTF-8": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_FR.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_HR.ISO8859-2": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_ES": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_CA.US-ASCII": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_CA.UTF-8": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hi_IN.ISCII-DEV": {
			InternationalCurrencySymbol: "INR",
			CurrencySymbol:              []byte{207, 222, 200, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 2},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_LT.ISO8859-4": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_NZ.US-ASCII": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_US.ISO8859-1": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_ES.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_PT.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_UA": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{208, 179, 209, 128, 208, 189, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_CZ.UTF-8": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 196, 141},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CA.ISO8859-1": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_IT.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_US.US-ASCII": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_ES.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_HU.UTF-8": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ja_JP.SJIS": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "no_NO.UTF-8": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_DE.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_GR.ISO8859-7": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_GR.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_BR": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_PT.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_UA.KOI8-U": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{199, 210, 206, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_CH.UTF-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_BE.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_RU.KOI8-R": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{210, 213, 194, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_HK.UTF-8": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_BY": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_CZ": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 196, 141},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_DE.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_ES": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_ES.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "is_IS": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "af_ZA.UTF-8": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_DK.ISO8859-15": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_IE": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{226, 130, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_RU.CP1251": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{240, 243, 225, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_BE.UTF-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CH.ISO8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_BE.ISO8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sk_SK.ISO8859-2": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "am_ET": {
			InternationalCurrencySymbol: "ETB",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_FI.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_FR.ISO8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_CA": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_FR": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hy_AM": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{212, 180, 213, 144},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_NL": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_YU.ISO8859-2": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_DE": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_NZ.ISO8859-1": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_FI": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_SE.UTF-8": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_CN.GBK": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		},
	}
)
