package monetary

var (
	localeNames = LocaleNames{
		"C",
		"POSIX",
		"af_ZA",
		"af_ZA.ISO8859-1",
		"af_ZA.ISO8859-15",
		"af_ZA.UTF-8",
		"am_ET",
		"am_ET.UTF-8",
		"be_BY",
		"be_BY.CP1131",
		"be_BY.CP1251",
		"be_BY.ISO8859-5",
		"be_BY.UTF-8",
		"bg_BG",
		"bg_BG.CP1251",
		"bg_BG.UTF-8",
		"ca_ES",
		"ca_ES.ISO8859-1",
		"ca_ES.ISO8859-15",
		"ca_ES.UTF-8",
		"cs_CZ",
		"cs_CZ.ISO8859-2",
		"cs_CZ.UTF-8",
		"da_DK",
		"da_DK.ISO8859-1",
		"da_DK.ISO8859-15",
		"da_DK.UTF-8",
		"de_AT",
		"de_AT.ISO8859-1",
		"de_AT.ISO8859-15",
		"de_AT.UTF-8",
		"de_CH",
		"de_CH.ISO8859-1",
		"de_CH.ISO8859-15",
		"de_CH.UTF-8",
		"de_DE",
		"de_DE.ISO8859-1",
		"de_DE.ISO8859-15",
		"de_DE.UTF-8",
		"el_GR",
		"el_GR.ISO8859-7",
		"el_GR.UTF-8",
		"en_AU",
		"en_AU.ISO8859-1",
		"en_AU.ISO8859-15",
		"en_AU.US-ASCII",
		"en_AU.UTF-8",
		"en_CA",
		"en_CA.ISO8859-1",
		"en_CA.ISO8859-15",
		"en_CA.US-ASCII",
		"en_CA.UTF-8",
		"en_GB",
		"en_GB.ISO8859-1",
		"en_GB.ISO8859-15",
		"en_GB.US-ASCII",
		"en_GB.UTF-8",
		"en_IE",
		"en_IE.UTF-8",
		"en_NZ",
		"en_NZ.ISO8859-1",
		"en_NZ.ISO8859-15",
		"en_NZ.US-ASCII",
		"en_NZ.UTF-8",
		"en_US",
		"en_US.ISO8859-1",
		"en_US.ISO8859-15",
		"en_US.US-ASCII",
		"en_US.UTF-8",
		"es_ES",
		"es_ES.ISO8859-1",
		"es_ES.ISO8859-15",
		"es_ES.UTF-8",
		"et_EE",
		"et_EE.ISO8859-15",
		"et_EE.UTF-8",
		"eu_ES",
		"eu_ES.ISO8859-1",
		"eu_ES.ISO8859-15",
		"eu_ES.UTF-8",
		"fi_FI",
		"fi_FI.ISO8859-1",
		"fi_FI.ISO8859-15",
		"fi_FI.UTF-8",
		"fr_BE",
		"fr_BE.ISO8859-1",
		"fr_BE.ISO8859-15",
		"fr_BE.UTF-8",
		"fr_CA",
		"fr_CA.ISO8859-1",
		"fr_CA.ISO8859-15",
		"fr_CA.UTF-8",
		"fr_CH",
		"fr_CH.ISO8859-1",
		"fr_CH.ISO8859-15",
		"fr_CH.UTF-8",
		"fr_FR",
		"fr_FR.ISO8859-1",
		"fr_FR.ISO8859-15",
		"fr_FR.UTF-8",
		"he_IL",
		"he_IL.UTF-8",
		"hi_IN.ISCII-DEV",
		"hr_HR",
		"hr_HR.ISO8859-2",
		"hr_HR.UTF-8",
		"hu_HU",
		"hu_HU.ISO8859-2",
		"hu_HU.UTF-8",
		"hy_AM",
		"hy_AM.ARMSCII-8",
		"hy_AM.UTF-8",
		"is_IS",
		"is_IS.ISO8859-1",
		"is_IS.ISO8859-15",
		"is_IS.UTF-8",
		"it_CH",
		"it_CH.ISO8859-1",
		"it_CH.ISO8859-15",
		"it_CH.UTF-8",
		"it_IT",
		"it_IT.ISO8859-1",
		"it_IT.ISO8859-15",
		"it_IT.UTF-8",
		"ja_JP",
		"ja_JP.SJIS",
		"ja_JP.UTF-8",
		"ja_JP.eucJP",
		"kk_KZ",
		"kk_KZ.PT154",
		"kk_KZ.UTF-8",
		"ko_KR",
		"ko_KR.CP949",
		"ko_KR.UTF-8",
		"ko_KR.eucKR",
		"lt_LT",
		"lt_LT.ISO8859-13",
		"lt_LT.ISO8859-4",
		"lt_LT.UTF-8",
		"nl_BE",
		"nl_BE.ISO8859-1",
		"nl_BE.ISO8859-15",
		"nl_BE.UTF-8",
		"nl_NL",
		"nl_NL.ISO8859-1",
		"nl_NL.ISO8859-15",
		"nl_NL.UTF-8",
		"no_NO",
		"no_NO.ISO8859-1",
		"no_NO.ISO8859-15",
		"no_NO.UTF-8",
		"pl_PL",
		"pl_PL.ISO8859-2",
		"pl_PL.UTF-8",
		"pt_BR",
		"pt_BR.ISO8859-1",
		"pt_BR.UTF-8",
		"pt_PT",
		"pt_PT.ISO8859-1",
		"pt_PT.ISO8859-15",
		"pt_PT.UTF-8",
		"ro_RO",
		"ro_RO.ISO8859-2",
		"ro_RO.UTF-8",
		"ru_RU",
		"ru_RU.CP1251",
		"ru_RU.CP866",
		"ru_RU.ISO8859-5",
		"ru_RU.KOI8-R",
		"ru_RU.UTF-8",
		"sk_SK",
		"sk_SK.ISO8859-2",
		"sk_SK.UTF-8",
		"sl_SI",
		"sl_SI.ISO8859-2",
		"sl_SI.UTF-8",
		"sr_YU",
		"sr_YU.ISO8859-2",
		"sr_YU.ISO8859-5",
		"sr_YU.UTF-8",
		"sv_SE",
		"sv_SE.ISO8859-1",
		"sv_SE.ISO8859-15",
		"sv_SE.UTF-8",
		"tr_TR",
		"tr_TR.ISO8859-9",
		"tr_TR.UTF-8",
		"uk_UA",
		"uk_UA.ISO8859-5",
		"uk_UA.KOI8-U",
		"uk_UA.UTF-8",
		"zh_CN",
		"zh_CN.GB18030",
		"zh_CN.GB2312",
		"zh_CN.GBK",
		"zh_CN.UTF-8",
		"zh_CN.eucCN",
		"zh_HK",
		"zh_HK.Big5HKSCS",
		"zh_HK.UTF-8",
		"zh_TW",
		"zh_TW.Big5",
		"zh_TW.UTF-8",
	}
	metaData = map[string]localeInfo{
		"c": {
			InternationalCurrencySymbol: "",
			CurrencySymbol:              nil,
			DecimalPoint:                nil,
			ThousandsSeparator:          nil,
			Grouping:                    []int8{0},
			PositiveSign:                nil,
			NegativeSign:                nil,
			FractionalDigits:            127,
		}, "posix": {
			InternationalCurrencySymbol: "",
			CurrencySymbol:              nil,
			DecimalPoint:                nil,
			ThousandsSeparator:          nil,
			Grouping:                    []int8{0},
			PositiveSign:                nil,
			NegativeSign:                nil,
			FractionalDigits:            127,
		}, "af_za": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_za.iso8859-1": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_za.iso8859-15": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "af_za.utf-8": {
			InternationalCurrencySymbol: "ZAR",
			CurrencySymbol:              []byte{82},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "am_et": {
			InternationalCurrencySymbol: "ETB",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "am_et.utf-8": {
			InternationalCurrencySymbol: "ETB",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_by": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_by.cp1131": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{224, 227, 161, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_by.cp1251": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{240, 243, 225, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_by.iso8859-5": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{224, 227, 209, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "be_by.utf-8": {
			InternationalCurrencySymbol: "BYR",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_bg": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{208, 187, 208, 178, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_bg.cp1251": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{235, 226, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "bg_bg.utf-8": {
			InternationalCurrencySymbol: "BGN",
			CurrencySymbol:              []byte{208, 187, 208, 178, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_es": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_es.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_es.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ca_es.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_cz": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 196, 141},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_cz.iso8859-2": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 232},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "cs_cz.utf-8": {
			InternationalCurrencySymbol: "CZK",
			CurrencySymbol:              []byte{75, 196, 141},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_dk": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_dk.iso8859-1": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_dk.iso8859-15": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "da_dk.utf-8": {
			InternationalCurrencySymbol: "DKK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_at": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_at.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_at.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_at.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_ch": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_ch.iso8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_ch.iso8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_ch.utf-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_de": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_de.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_de.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "de_de.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_gr": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_gr.iso8859-7": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "el_gr.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_au": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_au.iso8859-1": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_au.iso8859-15": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_au.us-ascii": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_au.utf-8": {
			InternationalCurrencySymbol: "AUD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ca": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ca.iso8859-1": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ca.iso8859-15": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ca.us-ascii": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ca.utf-8": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_gb": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{194, 163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_gb.iso8859-1": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_gb.iso8859-15": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_gb.us-ascii": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_gb.utf-8": {
			InternationalCurrencySymbol: "GBP",
			CurrencySymbol:              []byte{194, 163},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ie": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{226, 130, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_ie.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{226, 130, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_nz": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_nz.iso8859-1": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_nz.iso8859-15": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_nz.us-ascii": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_nz.utf-8": {
			InternationalCurrencySymbol: "NZD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_us": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_us.iso8859-1": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_us.iso8859-15": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_us.us-ascii": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "en_us.utf-8": {
			InternationalCurrencySymbol: "USD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_es": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_es.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_es.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "es_es.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_ee": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_ee.iso8859-15": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "et_ee.utf-8": {
			InternationalCurrencySymbol: "EEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_es": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_es.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_es.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "eu_es.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_fi": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_fi.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_fi.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fi_fi.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_be": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_be.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_be.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_be.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ca": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ca.iso8859-1": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ca.iso8859-15": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ca.utf-8": {
			InternationalCurrencySymbol: "CAD",
			CurrencySymbol:              []byte{36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ch": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ch.iso8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ch.iso8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_ch.utf-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_fr": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_fr.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_fr.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "fr_fr.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "he_il": {
			InternationalCurrencySymbol: "ILS",
			CurrencySymbol:              []byte{215, 169, 215, 151},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "he_il.utf-8": {
			InternationalCurrencySymbol: "ILS",
			CurrencySymbol:              []byte{215, 169, 215, 151},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hi_in.iscii-dev": {
			InternationalCurrencySymbol: "INR",
			CurrencySymbol:              []byte{207, 222, 200, 172},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 2},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_hr": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_hr.iso8859-2": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hr_hr.utf-8": {
			InternationalCurrencySymbol: "HRK",
			CurrencySymbol:              []byte{75, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_hu": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_hu.iso8859-2": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hu_hu.utf-8": {
			InternationalCurrencySymbol: "HUF",
			CurrencySymbol:              []byte{70, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hy_am": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{212, 180, 213, 144},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hy_am.armscii-8": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{184, 240},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "hy_am.utf-8": {
			InternationalCurrencySymbol: "AMD",
			CurrencySymbol:              []byte{212, 180, 213, 144},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "is_is": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "is_is.iso8859-1": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "is_is.iso8859-15": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "is_is.utf-8": {
			InternationalCurrencySymbol: "ISK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "it_ch": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_ch.iso8859-1": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_ch.iso8859-15": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_ch.utf-8": {
			InternationalCurrencySymbol: "CHF",
			CurrencySymbol:              []byte{70, 114, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_it": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_it.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_it.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "it_it.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ja_jp": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{194, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ja_jp.sjis": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ja_jp.utf-8": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{194, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ja_jp.eucjp": {
			InternationalCurrencySymbol: "JPY",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "kk_kz": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{209, 130, 208, 179, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "kk_kz.pt154": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{242, 227, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "kk_kz.utf-8": {
			InternationalCurrencySymbol: "KZT",
			CurrencySymbol:              []byte{209, 130, 208, 179, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ko_kr": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{226, 130, 169},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ko_kr.cp949": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ko_kr.utf-8": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{226, 130, 169},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "ko_kr.euckr": {
			InternationalCurrencySymbol: "KRW",
			CurrencySymbol:              []byte{92},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            0,
		}, "lt_lt": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_lt.iso8859-13": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_lt.iso8859-4": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "lt_lt.utf-8": {
			InternationalCurrencySymbol: "LTL",
			CurrencySymbol:              []byte{76, 116},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_be": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_be.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_be.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_be.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_nl": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_nl.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_nl.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "nl_nl.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_no": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_no.iso8859-1": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_no.iso8859-15": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "no_no.utf-8": {
			InternationalCurrencySymbol: "NOK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_pl": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 197, 130},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_pl.iso8859-2": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 179},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pl_pl.utf-8": {
			InternationalCurrencySymbol: "PLN",
			CurrencySymbol:              []byte{122, 197, 130},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_br": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_br.iso8859-1": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_br.utf-8": {
			InternationalCurrencySymbol: "BRL",
			CurrencySymbol:              []byte{82, 36},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_pt": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_pt.iso8859-1": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_pt.iso8859-15": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "pt_pt.utf-8": {
			InternationalCurrencySymbol: "EUR",
			CurrencySymbol:              []byte{69, 117},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ro_ro": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ro_ro.iso8859-2": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ro_ro.utf-8": {
			InternationalCurrencySymbol: "ROL",
			CurrencySymbol:              []byte{76, 101, 105},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru.cp1251": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{240, 243, 225, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru.cp866": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{224, 227, 161, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru.iso8859-5": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{224, 227, 209, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru.koi8-r": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{210, 213, 194, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "ru_ru.utf-8": {
			InternationalCurrencySymbol: "RUB",
			CurrencySymbol:              []byte{209, 128, 209, 131, 208, 177, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sk_sk": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sk_sk.iso8859-2": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sk_sk.utf-8": {
			InternationalCurrencySymbol: "SKK",
			CurrencySymbol:              []byte{83, 107},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_si": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_si.iso8859-2": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sl_si.utf-8": {
			InternationalCurrencySymbol: "SIT",
			CurrencySymbol:              []byte{83, 73, 84},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_yu": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_yu.iso8859-2": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_yu.iso8859-5": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{212, 216, 221},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sr_yu.utf-8": {
			InternationalCurrencySymbol: "YUD",
			CurrencySymbol:              []byte{100, 105, 110},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_se": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_se.iso8859-1": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_se.iso8859-15": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "sv_se.utf-8": {
			InternationalCurrencySymbol: "SEK",
			CurrencySymbol:              []byte{107, 114},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_tr": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_tr.iso8859-9": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "tr_tr.utf-8": {
			InternationalCurrencySymbol: "TRL",
			CurrencySymbol:              []byte{76},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{46},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_ua": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{208, 179, 209, 128, 208, 189, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_ua.iso8859-5": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{211, 224, 221, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_ua.koi8-u": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{199, 210, 206, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "uk_ua.utf-8": {
			InternationalCurrencySymbol: "UAH",
			CurrencySymbol:              []byte{208, 179, 209, 128, 208, 189, 46},
			DecimalPoint:                []byte{44},
			ThousandsSeparator:          []byte{},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{239, 191, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn.gb18030": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn.gb2312": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn.gbk": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn.utf-8": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{239, 191, 165},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_cn.euccn": {
			InternationalCurrencySymbol: "CNY",
			CurrencySymbol:              []byte{163, 164},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_hk": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_hk.big5hkscs": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_hk.utf-8": {
			InternationalCurrencySymbol: "HKD",
			CurrencySymbol:              []byte{72, 75, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_tw": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_tw.big5": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		}, "zh_tw.utf-8": {
			InternationalCurrencySymbol: "TWD",
			CurrencySymbol:              []byte{78, 84, 36},
			DecimalPoint:                []byte{46},
			ThousandsSeparator:          []byte{44},
			Grouping:                    []int8{3, 3},
			PositiveSign:                nil,
			NegativeSign:                []byte{45},
			FractionalDigits:            2,
		},
	}
)
